services:
  transaction_server1:
    build: ./transaction_server
    command: flask run --port=8000
    ports:
      - "8000:8000"
    links:
      - "database:db"
    volumes:
      - ./logs:/app/logs
  transaction_server2:
    build: ./transaction_server
    command: flask run --port=8001
    ports:
      - "8001:8001"
    links:
      - "database:db"
    volumes:
      - ./logs:/app/logs
  nginx_app:
    build: ./nginx_app
    ports:
      - "8002:8002"
    depends_on:
      - transaction_server1
      - transaction_server2
  database:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
#    volumes:
#      - mongodb_data_container:/data/db