services:
  transaction_server1:
    build: ./transaction_server
    command: flask run --port=8000
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - DB_HOST=mongos1
  transaction_server2:
    build: ./transaction_server
    command: flask run --port=8001
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
    environment:
      - DB_HOST=mongos2
  nginx_app:
    build: ./nginx_app
    ports:
      - "8002:8002"
    depends_on:
      - transaction_server1
      - transaction_server2
  mongos1:
    container_name: mongos1
    image: mongo
    command: mongos --port 27017 --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip_all
    ports:
      - 60000:27017
  mongos2:
    container_name: mongos2
    image: mongo
    command: mongos --port 27017 --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip_all
    ports:
      - 60001:27017
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --port 27017 --configsvr --replSet cfgrs --dbpath /data/db 
    ports:
      - 40001:27017
    volumes:
      - /quadra_mongo_cluster/cfgsvr1:/data/db
  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --port 27017 --configsvr --replSet cfgrs --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - /quadra_mongo_cluster/cfgsvr2:/data/db
  cfgsvr3:
    container_name: cfgsvr3
    image: mongo
    command: mongod  --port 27017 --configsvr --replSet cfgrs --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - /quadra_mongo_cluster/cfgsvr3:/data/db
  shard1svr1:
    container_name: shard1svr1
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --shardsvr --replSet shard1rs 
    ports:
      - 50001:27017
    volumes:
      - /quadra_mongo_cluster/shard1svr1:/data/db
  shard1svr2:
    container_name: shard1svr2
    image: mongo
    command: mongod --port 27017 --dbpath /data/db  --shardsvr --replSet shard1rs
    ports:
      - 50002:27017
    volumes:
      - /quadra_mongo_cluster/shard1svr2:/data/db
  shard1svr3:
    container_name: shard1svr3
    image: mongo
    command: mongod --port 27017 --dbpath /data/db  --shardsvr --replSet shard1rs
    ports:
      - 50003:27017
    volumes:
      - /quadra_mongo_cluster/shard1svr3:/data/db
  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --shardsvr --replSet shard2rs
    ports:
      - 50004:27017
    volumes:
      - /quadra_mongo_cluster/shard2svr1:/data/db
  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --shardsvr --replSet shard2rs
    ports:
      - 50005:27017
    volumes:
      - /quadra_mongo_cluster/shard2svr2:/data/db
  shard2svr3:
    container_name: shard2svr3
    image: mongo
    command: mongod --port 27017 --dbpath /data/db --shardsvr --replSet shard2rs
    ports:
      - 50006:27017
    volumes:
      - /quadra_mongo_cluster/shard2svr3:/data/db